# false-positive caused because we haven't tsan-instrumented libgcc_s. Multiple threads
# are racing on a call to __register_frame_info(), but that function appears to be correctly locked internally.
race:llvm::RuntimeDyldELF::registerEHFrames

# https://github.com/python/cpython/issues/128050
race:partial_vectorcall_fallback

# https://github.com/python/cpython/issues/128100
race:ensure_nonmanaged_dict

# https://github.com/openxla/xla/issues/20686
race:dnnl_sgemm

# https://github.com/numpy/numpy/issues/28041
race:get_initial_from_ufunc

# https://github.com/numpy/numpy/issues/28042
race:PyArray_UpdateFlags

# https://github.com/python/cpython/issues/128130
race_top:run_eval_code_obj

race:dump_traceback

# https://github.com/numpy/numpy/issues/28045  not sure about this one
race:arraymethod_dealloc

# https://github.com/python/cpython/issues/128133
race:bytes_hash

# https://github.com/python/cpython/issues/128137
race:immortalize_interned

# https://github.com/python/cpython/issues/128144
race_top:PyMember_GetOne

# https://github.com/python/cpython/issues/128657
race:py_digest_by_name
